print("What is your name?")
name=input()
print("What is your age?")
age=input()
print("What is your favourite colour?")
colour=input()
print("Your name is", name, ".")
print(name, "is", age, "years old.")
print(name,"'s favourite colour is", colour, ".")